### ISSUE TITLE
Request for Access to Preprocessed Datasets (FB15k-237 and WN18RR)

### ISSUE THREAD

**Issue by csjywu1** [taokz/FedR#2]
Hello, I am truly impressed by the awesomeness of your work, and I'm eager to further study it. With utmost respect for your achievements, I kindly request your consideration in sharing the preprocessed datasets, FB15k-237 and WN18RR, with me. Thank you.

**Comment by taokz** [comment]
Hi @woshiwu666 Nice to meet you. I have uploaded the zip files of the datasets in the [Fed_data folder ](https://github.com/taokz/FedR/tree/main/Fed_data).

**Comment by csjywu1** [comment]
Thank you for sharing the zip files of the datasets in the Fed_data folder. I have successfully received the files, and I appreciate your promptness in providing them.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kai ***@***.***&gt;; 
发送时间: 2023年8月1日(星期二) 中午12:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taokz/FedR] Request for Access to Preprocessed Datasets (FB15k-237 and WN18RR) (Issue #2)





 
Hi @woshiwu666 Nice to meet you. I have uploaded the zip files of the datasets in the Fed_data folder .
