### ISSUE TITLE
Reproducing Results

### ISSUE THREAD

**Issue by patil-abhishek** [taokz/FedR#4]
Hi, I was trying to use your model in my project. I tried running the model on 10 clients. While I'm getting the same mrr in FedR mode as in the paper, I'm getting a way higher mrr in Single mode as compared to the value in paper (reported in paper: 0.12, my value: 0.20). 

Please let me know if there's something wrong with the command. 
`!python main.py --data_path Fed_data/FB15K237/FB15K237-Fed10.pkl --name FB15k237_10_TransE_Single --run_mode Single --model TransE --one_client_idx 0 --early_stop_patience 3 --gpu 0`

I'm attaching the log file for 0th client for your reference.
[FB15k237_10_TransE_Single.log](https://github.com/taokz/FedR/files/13520104/FB15k237_10_TransE_Single.log)

**Comment by patil-abhishek** [comment]
None of the clients are giving mrr near 0.12. Did you claim false results in the EMNLP conference?

**Comment by taokz** [comment]
Hi @patil-abhishek,

The results reported in the paper are the average mrr across all clients. It seems in your experiment, you got the result of the client 0 (the first one). You can get all the results of all clients and perform average.

**Comment by patil-abhishek** [comment]
The average of all clients is 0.20935. This is actually higher than the FedR mode mrr. I'd like to know how you got the difference proposed in your paper.

Attaching both the logs and the notebook for your reference.

[fb15k237_10.zip](https://github.com/taokz/FedR/files/13595700/fb15k237_10.zip)
